name: Frontend Build

on:
  push:
    branches: [master]
    paths: [frontend/**, .github/workflows/frontend-build.yml]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: ./src-repo
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/setup-node@v1
      - name: Install Dependencies
        run: yarn install
        working-directory: ./src-repo/frontend
      - name: Build the frontend
        run: yarn build
        working-directory: ./src-repo/frontend
      - name: Generate the site
        run: yarn generate
        working-directory: ./src-repo/frontend

      - uses: actions/checkout@v2
        with:
          repository: thejcannon/strickland-cannon-coop
          path: ./docs-repo
          token: ${{ secrets.DOCS_REPO_TOKEN }}
      - name: Wipe docs repo clean
        run: |
          shopt -s extglob
          rm -rf !(data)
          working-directory: ./src-repo/frontend
      - name: Move generated docs into repo
        run: |
          shopt -s dotglob nullglob
          mv ./src-repo/frontend/dist/* ./docs-repo
      - uses: EndBug/add-and-commit@v4
        with:
          add: ". -A"
          cwd: ./docs-repo
          message: "Build from ${{ env.GITHUB_SHA_SHORT }}"
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_REPO_TOKEN }}
