name: Frontend Build

on:
  push:
    branches: [ master ]
    paths: [frontend/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: './src-repo'
    - uses: actions/setup-node@v1
    - name: Install Dependencies
      run: yarn install
      working-directory: ./src-repo/frontend
    - name: Build the Frontend
      run: yarn build
      working-directory: ./src-repo/frontend
    - name: Generate the site
      run: yarn generate
      working-directory: ./src-repo/frontend

    - uses: actions/checkout@v2
      with:
        repository: thejcannon/strickland-cannon-coop
        path: ./docs-repo
    - name: Wipe docs repo clean
      run: rm -rf ./docs-repo/*
    - name: Move generated docs into repo
      run: mv ./src-repo/frontend/dist/* ./docs-repo
    - uses: EndBug/add-and-commit@v4
      with:
        add: '. -A'
        cwd: './docs-repo'
        message: 'Build from ${{ GITHUB_SHA }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
